#!/bin/sh
#
# Note that we rsync the drupal cvs to speed up the things, as documented
# at http://drupal.org/node/277268. However we only rsync the directories
# of the modules needed - not the whole big CVS.

cd `dirname $0`

# Include our configuration options.
. ./drupal_sync.conf

QUIET="-q"
if [ ! $VERBOSE = "0" ]; then
  QUIET=""
fi

export CVSROOT=$CVSROOT

if [ $# -gt 0 ]; then
  LIST=$*
else
  LIST=$MINE
fi
    
#init local cvs repo
mkdir -p $CVSSRV
if [ ! -d $CVSSRV/CVSROOT ]; then
  cvs -d$CVSSRV init
  chmod u+w $CVSSRV/CVSROOT/modules
  echo "drupal drupal\ncontributions contributions" >> $CVSSRV/CVSROOT/modules
  chmod u-w $CVSSRV/CVSROOT/modules
fi
 
for module in $LIST
do
  mkdir -p $GITSRV/$module
  mkdir -p $CVSSRV/contributions/modules/$module
  # That way the files go into $module/$module. Doing so lets cvs work right
  # althoug the repository isn't complete. Don't know why, but it works.
  rsync -avz --delete cvs.drupal.org::cvsmirror-contrib/contributions/modules/$module $CVSSRV/contributions/modules/$module/ #> /dev/null 2>&1

  cd $GITSRV/$module
  #update git from local cvs mirror
  # -k is important for cvs ids being replaced with $Id$
  # -o master makes sure the branch for HEAD is named "master"
  git cvsimport -i -k -o master -a -p "-x,$QUIET" -v -d $CVSSRV contributions/modules/$module/$module
done


